### ISSUE TITLE
Display error messages from the command with BAlert

### ISSUE THREAD

**Issue by BachToTheFuture** [HaikuArchives/ZooKeeper#9]
Currently, ZooKeeper can only show error messages in the console. It would be helpful if the users can see error messages as an alert box.

**Comment by BachToTheFuture** [comment]
Got it working.

**Comment by scottmc** [comment]
Can you post a screenshot showing an error message?

**Comment by BachToTheFuture** [comment]
@scottmc It looks something like this:

![](https://raw.githubusercontent.com/bach5000/dummy/master/Bitmap%20Clip.png)
